### ISSUE TITLE
Version of the toolchain

### ISSUE THREAD

**Issue by Chester-zZz** [dongfangduoshou123/YoloV3-TensorRT#1]
Appreciate your work.
Could you please tell me your versions of toolchain?
Including python, onnx, etc.
TensorRT I know is 6.0.1.5. 
After some modifications, I can compile the code, but when I run it, I found that parser couldn't pasr the onnx file. With this warning:

> WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).

My onnx is 1.4.1, and only with this version or 1.4.0 can the darknet weights be converted.

I modified the network creation code from createNetworkV2 to createNetwork, the parser seems to work but there comes a serialize problem.

So, could you please show your versions of toolchain? Thank you.

**Comment by dongfangduoshou123** [comment]
"""This sample is not supported on Ubuntu 14.04 and older. Additionally, the `yolov3_to_onnx.py` script does not support Python 3""" as intruduced in the yolov3_onnx dir's Readme.

so I use python2.7 with onnx version 1.5.0
And now you could parse and serialize the engine use seralizeEngineFromPythonAPI.py..dese not need the yolo_onnx sample's support.
