### ISSUE TITLE
请教一下plugincreator的用法？

### ISSUE THREAD

**Issue by dancingpipi** [dongfangduoshou123/YoloV3-TensorRT#14]
在tensorrt官网找了一圈没找到关于creator的文档。
麻烦请问一下我自定义了一个LReluPluginCreator，getPluginName设置的名字是“LRelu”，那么我只需要在代码里REGISTER_TENSORRT_PLUGIN(LReluPluginCreator)就行了吗？prototxt怎么改呢？是把layer type改为"LRelu"吗？

**Comment by dongfangduoshou123** [comment]
这种中间层有同时caffe和trt不支持的情况的话，建议不用parser来解析，自己手动写脚本转换吧。
