### ISSUE TITLE
网络没有输出值

### ISSUE THREAD

**Issue by wendinghe** [dongfangduoshou123/YoloV3-TensorRT#16]
我现在主要的问题是虽然整个demo能跑通了，能显示结果图，但没有检测框。导致这个问题的原因主要是网络没有返回值，请问下有什么好的解决方案吗？

**Comment by wendinghe** [comment]
@Learner0918 通过翻看之前记录，发现您也遇到过类似问题，请问您是怎么解决这个问题的？

**Comment by wendinghe** [comment]
问题解决了

**Comment by nicolasgorrity** [comment]
Hello,
I am encountering the same problem as you.
All the output values are zero.
How did you solve the issue?

**Comment by uCedar** [comment]
@wendinghe 我也遇到了同样的问题，看到您已经解决，请问是怎么解决的？

**Comment by zhangyilalala** [comment]
请问有人解决了这个没有输出的问题吗？能指点一下吗？

**Comment by dongfangduoshou123** [comment]
有肯定是有的，就是不愿意分享一下。https://github.com/dongfangduoshou123/YoloV3-TensorRT/issues/9 还有这个人wendinghe他们都解决了的。

**Comment by zhangyilalala** [comment]
@Learner0918 请问能说一下没有检测框这个问题大致是什么原因吗？非常感谢！

**Comment by zhangyilalala** [comment]
@dongfangduoshou123 我现在发现框的x,y是有输出的，但是w,h 置信度都是0，哎再调试看看

**Comment by wendinghe** [comment]
我是根据@Learner0918 代码仓库里进行修改的，那个tensorRT的环境注意下 跑的是7，其他的小细节，我也不记得了 ，自己去看下

**Comment by zhangyilalala** [comment]
好的，我去试下，谢谢！



---原始邮件---
发件人: "wendinghe"<notifications@github.com&gt;
发送时间: 2020年3月25日(周三) 晚上8:10
收件人: "dongfangduoshou123/YoloV3-TensorRT"<YoloV3-TensorRT@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"zhangyilalala"<4413153@qq.com&gt;;
主题: Re: [dongfangduoshou123/YoloV3-TensorRT] 网络没有输出值 (#16)




 
我是根据@Learner0918 代码仓库里进行修改的，那个tensorRT的环境注意下 跑的是7，其他的小细节，我也不记得了 ，自己去看下

**Comment by zhangyilalala** [comment]
@dongfangduoshou123 yoloPlugin.cpp里面215 253行的 gridsize应该是gridesize，这里写错了所以封模型时候python的值没有对上这个属性名没传进去，所以网络执行kernel的时候gridesize是0就没输出了

**Comment by dongfangduoshou123** [comment]
好的，谢谢，算是解决了，关了它。
