### ISSUE TITLE
How can I add custom layer on this?

### ISSUE THREAD

**Issue by dsgh2** [dongfangduoshou123/YoloV3-TensorRT#22]
Hi, 
Thanks for this nice work first!

I am going to try to add custom layer function on this code.
If you do not mind, please let me know any general steps to do.

I am struggling because of lack of guides(actually not enough for me)

Thanks in advance.

**Comment by dongfangduoshou123** [comment]
Please refer to the yolo.h、yolo.cpp in this repo.
