### ISSUE TITLE
 [TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input

### ISSUE THREAD

**Issue by peif1987** [dongfangduoshou123/YoloV3-TensorRT#5]
Thanks for your great work. 
I have successfully complied the project, and got the libyoloPlugin.so and excetable bin file:TensorRTYOLOV3.
Then I follow your instruction, use (TensorRT-ROOT/samples/python/yolov3_onnx) to convert the yolov3 model to  yolov3.onnx. and then use seralizeEngineFromPythonAPI.py to convert it to trt model. But I met the following error:

>  [TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input
I have checked the yolov3.cfg, and sure that the input size is (1,3,608,608). 
Could you please help me to solve the problem?

**Comment by dongfangduoshou123** [comment]
I use Onnx 1.5.0
TensroRT 6.0.1.5
I have convert the 416X416 version yolov3 ok!
608 has not tested, but should also ok.
The SampleYolov3.cpp now can directly parse the yolov3.onnx, serialize it and run inference.
you 608 version some parameters should be modified.
