### ISSUE TITLE
Using .weights and .cfg

### ISSUE THREAD

**Issue by ttdd11** [dongfangduoshou123/YoloV3-TensorRT#7]
Does this use .weights and .cfg from darknet? If so I may try on windows using rtx 2080ti and post speeds.

**Comment by dongfangduoshou123** [comment]
I use the TensorRT's yolov3 python example's script(location at TensorRT-ROOT/samples/python/yolov3_onnx), to convert the yolov3 model from darknet（.weights and .cfg) to onnx format named yolov3.onnx
